Adding pubtools-pyxis-get-signatures [CLOUDDST-4422]
release-engineering/pubtools-pyxis pull request #13
Opened 2021-03-05 13:47 UTC by chandwanitulsi

pubtools-pyxis-get-signature entrypoint is added to
get container signature metadata from pyxis matching
the given paramaters like manifest_digest, reference,
sig_key_id

2021-03-08 13:23 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +}
nitpicking: no empty lines, two empty lines, one empty line.

2021-03-08 13:23 UTC, neithere commented on tests/test_pyxis_client.py
> +    hostname = "https://pyxis.engineering.redhat.com/"
It would be better to use the same dummy URL as in other tests.

2021-03-08 19:05 UTC, neithere commented
By the way, once this is merged, can we tag it as a new release to pin the package in Pub's requirements?

2021-03-09 21:01 UTC, chandwanitulsi commented
@midnightercz , @querti @lipoja @yashvardhannanavati @pbortlov, could you please review

2021-03-10 12:47 UTC, pbortlov requested changes

2021-03-10 12:47 UTC, pbortlov commented on pubtools/_pyxis/pyxis_client.py
> +        if manifest_digests:
What will happen if there are more manifest_digests arguments in the string? Should we split it by commas first?

2021-03-10 12:47 UTC, pbortlov commented on pubtools/_pyxis/pyxis_client.py
> +            filter_urls.append("manifest_digest=in=({0}),".format(manifest_digests))
Is it any particular reason we use `{0}` and format()? Could we use `f'manifest_digest=in=({manifest_digests}),'` instead?

2021-03-10 12:47 UTC, pbortlov commented on pubtools/_pyxis/pyxis_client.py
> +    def get_container_signatures(self, manifest_digests, references, sig_key_ids):
If `manifest_digests`, `references`, `sig_key_ids` are optional can we mofidy it to e.g. `manifest_digest=None`?

2021-03-10 12:47 UTC, pbortlov commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
What if `args.manifest_digest`, `args.reference`, `args.sig_key_id` are not available? What does it return?

2021-03-10 12:47 UTC, pbortlov commented on tests/test_data/sigs_with_reference.json
> +]
What does it mean? Is it missing empty line?

2021-03-10 12:47 UTC, pbortlov commented on tests/test_pyxis_client.py
> +    hostname = "https://pyxis.engineering.redhat.com/"
Would you mind creating a file and pull `hostname` from there to all the test cases if it is neeeded? example https://gitlab.cee.redhat.com/content-delivery/qe/iib-api-test/-/blob/master/tests/conftest.py

2021-03-10 12:47 UTC, pbortlov commented on tests/test_data/sigs_with_reference.json
> +[
This seems to be real data. Could we mock it?

2021-03-10 15:26 UTC, neithere commented on tests/test_data/sigs_with_reference.json
> +]
It's missing `\n`, I believe.

2021-03-10 17:20 UTC, querti submitted a review, later dismissed

2021-03-10 17:20 UTC, querti commented on pubtools/_pyxis/pyxis_client.py
> +                signatures_url = "{0}{1}".format(signatures_url, filter_url)
This is essentially just a string concatenation? why is it written like this?

2021-03-10 17:20 UTC, querti commented on pubtools/_pyxis/pyxis_client.py
> +        signatures_url = "signatures"
this is only an endpoint, not a url, right?

2021-03-10 17:29 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
Definitely not at the moment.

So there are two distinct action items:
* decide how strictly we follow the existing use case — either allow anything or require all three arguments;
* discuss/decide what to do with pagination (potentially relevant even if all three args are required).

2021-03-12 14:26 UTC, midnightercz requested changes

2021-03-12 14:26 UTC, midnightercz commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
I think it makes sense to support pagination

2021-03-12 14:26 UTC, midnightercz commented on tests/test_pyxis_client.py
> +    hostname = "https://pyxis.engineering.redhat.com/"
definitely it shouldn't be the real hostname

2021-03-15 12:19 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
Should we then retrieve all the pages and give them to Pub as one list?

2021-03-16 12:57 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_client.py
> +        resp = self.pyxis_session.get(signatures_url)
I am thinking it might be better to split requests from pub such that the entry-point is called multiple times by specifying limited parameters for each pubtools-pyxis-get-signature call, thoughts?

2021-03-16 12:57 UTC, chandwanitulsi commented on tests/test_pyxis_ops.py
> +    hostname = "https://pyxis.engineering.redhat.com/"
yup, I missed that, updating in next commit

2021-03-16 13:01 UTC, chandwanitulsi commented on README.rst
> +  --sig-key-id <sig_key_id>
I am thinking let me change my addition from "<string>" to more explanatory values to keep README consistent and push the change in next commit and then we can determine if it needs more changes

2021-03-16 14:33 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_client.py
> +        if manifest_digests:
more manifest_digests are accepted if they are separated by comma, we don't need to split it, we can directly use the comma separated manifests in our filter query
for example, if entry-point is called with --manifest-digest md1,md2 filter query for getting signatures from pyxis will be .../v1/signatures?filter=manifest_digests=in=(md1,md2)

2021-03-16 14:35 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_client.py
> +            filter_urls.append("manifest_digest=in=({0}),".format(manifest_digests))
As explained above py3.6 plus can only be used if I use suggested formatting

2021-03-16 14:35 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_client.py
> +    def get_container_signatures(self, manifest_digests, references, sig_key_ids):
Updating in next commit

2021-03-16 14:35 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
Updating in next commit

2021-03-16 14:45 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +GET_SIGNATURES_ARGS[("--manifest-digest",)] = {
The reason I went with this approach was that I wanted to allow supporting multiple parameters in calling entry-point and if we allow append action entry-point could end up potentially having several manifest_digest and several references making it quite a long call, and eventually I need to pass comma separated values anyway in filter query so with this way I can directly use the given parameter value.
Also I noticed there were other pubtools entrypoints going with same approach. 
If there are still any strong objections for this approach I can modify it to use append action

2021-03-16 14:48 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_client.py
> +            signatures_url = "{0}{1}".format(signatures_url, "?filter=")
get signatures API doesn't allow passing parameters to retrieve signatures by filtering on the given field, hence constructing the filter query URL
@neithere please correct me if I missed something here

2021-03-16 14:49 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_client.py
> +                signatures_url = "{0}{1}".format(signatures_url, filter_url)
updating in next patch, let me know if you still have questions

2021-03-16 14:51 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
Currently we don't have an exact use case for getting all signatures wrt to pub, but instead of creating an entry-point with rigid parameters I thought I can make it flexible enough to be used in various use cases

2021-03-16 14:55 UTC, querti commented on pubtools/_pyxis/pyxis_ops.py
> +GET_SIGNATURES_ARGS[("--manifest-digest",)] = {
It can be left as-is I think

2021-03-16 18:18 UTC, neithere commented on pubtools/_pyxis/pyxis_client.py
> +        resp = self.pyxis_session.get(signatures_url)
Pub essentially calls a normal function and it would be strange to have limits on the length of Python function arguments. I'd rather consider this an implementation detail and do the split/join inside pubtools. We may need to do some de-duplication on top of that, otherwise doesn't seem too complicated.

2021-03-16 18:23 UTC, neithere commented on pubtools/_pyxis/pyxis_client.py
> +            signatures_url = "{0}{1}".format(signatures_url, "?filter=")
Correct. We have to construct a RSQL expression for the `filter` parameter.

2021-03-18 19:05 UTC, neithere approved these changes

2021-03-18 19:05 UTC, neithere commented on pubtools/_pyxis/pyxis_client.py
> +    def _get_all_pages_response(self, endpoint, **kwargs):
Maybe `_get_items_from_all_pages` or something like that?

2021-03-19 16:29 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_client.py
> +        filter_criterias = []
Aah in making sure I was using the right singular, missed changing this

2021-03-22 11:32 UTC, midnightercz requested changes
Looks good, but please implement there filter check e.i. at least one criterion has to be specified

2021-03-22 11:32 UTC, midnightercz commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
> Should we then retrieve all the pages and give them to Pub as one list?
That doesn't make sense. In _get_all_pages_response you iterate over all pages which means without any filters specified you would get all signatures in pyxis. I don't see use-case for that. Also it's not really efficient. 
At least one filter attribute has to be specified otherwise tool should fail

2021-03-22 12:04 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +        res = pyxis_client.get_container_signatures(
Just to clarify: all-pages-as-one-list does make sense with a mandatory filter but doesn't without one, right?
So in order to avoid a huge amount of data being downloaded at once we should either limit to one page without filters and require an explicit page number (but then we need to return the data in a different format with page metadata) or require at least one mandatory filter to be specified. The latter seems the most reasonable.

2021-03-23 02:31 UTC, zxiong commented
> Looks good, but please implement there filter check e.i. at least one criterion has to be specified

We might need to create more indexes for each filter field to void long search time. One of example, I did a test to do a query a filter with "reference" only, it took around 60 second (there are 20,000,000 signatures in the containerSignature)

I'd suggest only implementing filters as need instead of more to avoid bringing unexpected performance issue.

2021-03-24 19:52 UTC, chandwanitulsi commented
> > Looks good, but please implement there filter check e.i. at least one criterion has to be specified
> 
> We might need to create more indexes for each filter field to void long search time. One of example, I did a test to do a query a filter with "reference" only, it took around 60 second (there are 20,000,000 signatures in the containerSignature)
> 
> I'd suggest only implementing filters as need instead of more to avoid bringing unexpected performance issue.

Was this performance degrade even after having compound index? I mean even after having compound index for manifest_digest, reference and sig_key_id, we should have separate index for each filter we would like to use?

In that case is having all three (manifest_digest, reference and sig_key_id) as filters really useful? Maybe we should stick to only manifest_digest or 2( max manifest_digest and reference)

2021-03-24 23:27 UTC, chandwanitulsi commented
I have pushed another commit keeping just manifest_digest and reference, if I need to remove reference as well, will do that in next commit

2021-03-25 01:39 UTC, zxiong commented
> > > Looks good, but please implement there filter check e.i. at least one criterion has to be specified
> > 
> > 
> > We might need to create more indexes for each filter field to void long search time. One of example, I did a test to do a query a filter with "reference" only, it took around 60 second (there are 20,000,000 signatures in the containerSignature)
> > I'd suggest only implementing filters as need instead of more to avoid bringing unexpected performance issue.
> 
> Was this performance degrade even after having compound index? I mean even after having compound index for manifest_digest, reference and sig_key_id, we should have separate index for each filter we would like to use?

Yes, besides the compound index, we should have separate index for each filter, because the compound index (manifest_digest, repository, reference, sig_key_id) just works for the filter which contains the first field "manifest_digest". Otherwise, queries will not use the index (see https://docs.mongodb.com/manual/core/index-compound/#prefixes), eg: db.containerSignature.find({"reference" : "xxxx"})

> In that case is having all three (manifest_digest, reference and sig_key_id) filters really useful? Maybe we should stick to only manifest_digest or 2 max (manifest_digest and reference)

If we stick to only manifest_digest, besides the compound index, no addition indexes are needed to create.

If we stick to manifest_digest and reference, an additional index on reference needs to create for the queries which only has manifest_digest in the filter, eg:  db.containerSignature.find({"reference" : "xxxx"})

AFAIK, CLOUDDST-4394 only contains manifest_digest in the filter, I don't see any cases which have reference and sig_key_id in the filter. So I suggest sticking to only manifest_digest.

2021-03-26 19:35 UTC, yashvardhannanavati approved these changes
Couple of optional comments :)

2021-03-26 19:35 UTC, yashvardhannanavati commented on pubtools/_pyxis/pyxis_client.py
> +            signatures_endpoint, "?filter=", "".join(filter_criteria)
You can probably add `?filter=` in the string itself?

2021-03-26 19:35 UTC, yashvardhannanavati commented on pubtools/_pyxis/pyxis_client.py
> +        signatures_endpoint = signatures_endpoint[0:-1]
optional: `signatures_endpoint[0:-1]` => `signatures_endpoint[:-1]`

2021-03-29 13:12 UTC, midnightercz approved these changes

2021-03-29 13:27 UTC, merged