Added the ability to add file as input type for --manifest_digests and --reference for get-signatures
release-engineering/pubtools-pyxis pull request #18
Opened 2021-04-19 05:06 UTC by chandwanitulsi

2021-04-19 12:34 UTC, querti submitted a review, later dismissed
Could you also pls maintain 100% coverage? Thanks

2021-04-19 12:34 UTC, querti commented on pubtools/_pyxis/pyxis_ops.py
> +            file_content_json = json.load(f)
Not sure I understand this. is CSV expected to be parsable as json?

2021-04-19 12:34 UTC, querti commented on pubtools/_pyxis/pyxis_ops.py
> +def _get_string_or_file_contents(value, str_format=None):
Could you document the possible values in the description?

2021-04-19 15:23 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +            file_content_json = json.load(f)
The file input would be json something like ["digest1","digest2"], but for get_signatures_main() I need comma separated string like "digest1,digest2". str_format signifies the return format

2021-04-19 15:24 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +def _get_string_or_file_contents(value, str_format=None):
sure, for now only "csv" format is used for get_signatures(), for upload_signatures() just file read as string is enough

2021-04-28 22:35 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
>          parser.error("Give atleast 1 filter, --manifest_digest and/or --reference")
Should be `--manifest-digest`, with a hyphen. Not important and not 100% relevant to this PR but I remember being confused when I got this error and copy-pasted this argument name :)

2021-04-28 22:35 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +def _get_string_or_file_contents(value, str_format=None):
Hm, it seems that the function is doing too much: it decides what is passed, it conditionally loads a file and conditionally deserializes and then serializes again its contents using different formats.

I'd rather have a function that gets something and a function that processes something. For example:
* `_get_string_or_file_contents(json_or_file_path: str)` and
* `_json_list_to_csv(json_data: str)`.

2021-04-29 02:42 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
>          parser.error("Give atleast 1 filter, --manifest_digest and/or --reference")
you are right, even I noticed this mistake when I was trying something else, but I forgot to fix it, thanks for bringing this

2021-04-29 02:43 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +def _get_string_or_file_contents(value, str_format=None):
yeah I was trying not to duplicate already written code in that function so I chose using parameter approach

2021-04-30 06:41 UTC, midnightercz requested changes

2021-04-30 06:41 UTC, midnightercz commented on pubtools/_pyxis/pyxis_ops.py
> +            file_content_json = json.load(f)
So you want to support both json and csv? So file for signatures is expected to be csv but for rest jsons are expected? I don't understand that, it should be unified

2021-04-30 15:41 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +            file_content_json = json.load(f)
when uploading signatures, a jsonified string is enough to send in post call, but for manifests and references, the input needs to be added in the URL as a comma separated string. for example, to get signatures matching manifest_digest1 and manifest_digest2, the file input would be json containing ["manifest_digest1", "manifest_digest2"] and this function will convert it to comma separated string "manifest_digest1,manifest_digest2" to be used for url "/v1/signatures/filter=manifest_digest=in=(manifest_digest1,manifest_digest2)"
the str_format is the return format not input format, I think that's creating confusions?

2021-05-03 07:08 UTC, midnightercz commented on pubtools/_pyxis/pyxis_ops.py
> +            file_content_json = json.load(f)
Yeah, it kinda does. Maybe two functions would be better

2021-05-07 14:57 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +def get_csv_string_from_input_or_file(value):
I have added 2 functions/approaches for processing input for --manifest_digest/--reference,the input could be directly passed comma separated string like "md1,md2" or it could be json file with contents like '["md1","md2"]' .  In this function get_csv_string_from_input_or_file(), there is a little but of duplicated code, but IMO it makes reading code and function's use clearer. this function can be directly used (see commented line #285,

for the other approach 2 functions _get_string_or_file_contents and convert_string_to_csv needs to be used, first the string obtained by reading json file and then it is converted into comma separated values (which should be used in url to get signatures)

2021-05-10 22:03 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +def convert_string_to_csv(value):
Ah yes, the file read() returned as string so I continued with that. I can change the function name. 
Could you share your thoughts on using the 2 functions vs 1 function with some duplication? I personally feel having 1 function is making it easier but I would like to know what others think

2021-05-10 22:55 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +        return value
I don't think you can be confident that it's a "csv string" if it simply doesn't start with an `@`. It could be anything.

In the current form the correct function name would be rather "use verbatim value or, if possible, load list from given file in format A and serialize it to format B" :) the function is small but still does a lot of very different things at once.

This is why I'd rather suggest splitting it to smaller logical pieces (in pseudocode):
```
def deserialize_list_from_arg(value: str) -> list:
    if value starts with "@"
        read from file and deserialize as JSON
    else
        deserialize string as CSV

def serialize_list_for_request(value: list) -> str:
    join list with comma (or whatever is applicable)

param = serialize_list_for_request(deserialize_list_from_arg(args.manifest_digest))
```

The pseudocode above ensures that each unit of code has a single purpose and does just one thing without assumptions about another unit. It also keeps a normalized, deterministic value between the units, thus ensuring the separation of concerns.

Note that it may look very similar to the current option with two functions, but it's not: `get_string_or_file_contents()` returns a string in undefined format and `convert_string_to_csv()` attempts to guess that format, which makes the boundaries between units of code fuzzy and the logic tangled.

As mentioned, this is a very simple case and it's not worth a long discussion per se, so I'm ready to approve whatever approach you choose here; it just seems to be a useful example.

2021-05-12 14:05 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +        return value
As discussed, the above suggestion will not work as is because this way deserialize_list_from_arg() can only be used for get signatures --manifest-digest or --reference value, it cannot be used for post signatures --signatures value.
In get we pass the comma separated values if directly passed, while in post the input it always json, either directly passed or given as file. Will have to either use hack to work around this, or go all all-json i.e. all inputs in json form, file content or directly passed

2021-05-12 19:51 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +            file_content_json = json.load(f)
resolving this conversation as lot of open threads are creating confusion,the latest commit has 2 functions focusing on a single part

2021-05-13 19:58 UTC, neithere approved these changes

2021-05-13 19:58 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +    `gcc -o`, `curl -d`, etc.) and returns its contents in list if applicable;
"returns in list, otherwise as a list" — that's confusing.

Maybe just "returns its contents if applicable, otherwise returns the value itself. The return value is a `list`".

Note that while the documentation states "...as a list", in fact we just return whatever was in the file without validation. So we should either validate or warn the reader that we in fact just deserialize something from JSON and hope for the best. :)

2021-05-13 19:58 UTC, neithere commented on pubtools/_pyxis/pyxis_ops.py
> +def serialize_to_json(list_value):
Not sure if this pair of thin wrappers is needed. No harm though.

2021-05-14 07:25 UTC, midnightercz approved these changes

2021-05-14 13:09 UTC, chandwanitulsi commented on pubtools/_pyxis/pyxis_ops.py
> +def serialize_to_json(list_value):
yeah its kind of not needed to put that in a separate function, I let it be if that helps is easy readability and understanding

2021-05-14 13:21 UTC, chandwanitulsi commented
> Could you also pls maintain 100% coverage? Thanks

Coverage is increased to 100% now

2021-05-18 13:34 UTC, querti approved these changes

2021-05-19 13:37 UTC, merged